env:
  SECRET_CODECOV_TOKEN: "..."

steps:
  # Julia versions

  - label: "Julia 1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6-nightly
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120
