env:
  SECRET_CODECOV_TOKEN: "..."

steps:
  # Julia versions

  - label: "CUDA 11.2"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6-nightly
      - JuliaCI/julia-test#v1:
          test_args: "--thorough"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "11.2"
      cap: "recent"
    env:
      JULIA_CUDA_VERSION: '11.2'
      JULIA_CUDA_USE_BINARYBUILDER: 'true'
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120
